[project]
name = "pysenxor-master"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cmapy>=0.6.6",
    "crcmod>=1.7",
    "imutils>=0.5.4",
    "matplotlib>=3.10.3",
    "numpy>=2.3.1",
    "opencv-python>=4.11.0.86",
    "setuptools>=80.9.0",
    "smbus>=1.1.post2",
]
